### ISSUE TITLE
Seperatre neutronJS from express

### ISSUE THREAD

**Issue by wer** [VanCoding/neutronJS#1]
Very nice start, but i think its not necessary to unclude express in your cms.
I would try to keep it standalone.

**Comment by VanCoding** [comment]
Hi @wer 

Express is an important part of neutronJS at the moment and I don't think it makes sense reimplement everything express does just to be independent of it. Actually, it's more like a feature that it uses express, since it's compatible with so much cool express modules out there.

Modules that don't depend on express usually depend upon another comparable library, which also would make them incompatible with neutronJS. There are not much "vanilla" node.js modules out there. Express is by far the leader right now, which is reason #1 why i chose it. Reason #2 is that it's really great since version 4 and perfectly matches the design of neutronJS. I think it would be a shame to not use it.

The only alternative I've thought about was koa, but since code that uses generators would have to be transpiled for running in the browser I've decided to not use it yet. I might switch over when generators reach the browsers, though.

So, after explaining my point a bit, could you maybe give me some arguments or use cases of when it could be useful when neutronJS is express-independent?

**Comment by wer** [comment]
Reading the description of neutronJS, i thought that this would be a library on top of react.js to create views based on a configuration.
Personally i think of a structure where you dont need to know if you are in front or backend.

**Comment by VanCoding** [comment]
Oh well, I think you have misunderstood what neutron does then. It's not just a view library. It also provides a system for routing and data handling. It should help build pages that must be WYSIWYG editable for non-programmer users.
