### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by lennerd** [VanCoding/neutronJS#2]
Hey @VanCoding,

it may sound crazy or funny, but as I'm working with apostrophe right now and for the first time, I started to think about a possible CMS built on the ideas of apostrophe (and keystones model based admin area) and react components combined. I started to take some notes, thought about possible API methods etc.

And than I stumbled across your neutronJS. It's funny how close it actually is to my basic ideas.

So I wonder, what is the status of this project? Is it still maintained? Is there a roadmap or a basic plan? How can somebody help?

**Comment by VanCoding** [comment]
Hi @lennerd 

Nice! As it seems there are a lot of people interested in a CMS like this.

So what's the status of the project...
As you can see, I haven't done any work on it for quite a long time now and it might already seem to be dead. But that's not the case. I need neutronJS in the future!

_Quite_ a while ago, I was doing basic websites for people in PHP. Then Node.js happened, and since its release I've used it more and more. I totally love it :) But since people usually want their websites to be editable to some degree, I couldn't do it in Node.js because there was no CMS that really statisfied me. I was so sad about not being able to use Node.js for making editable websites for people, that I stopped doing websites for quite some time.

But I still got requested by people after that time. I've started to look at the first CMSes available for node (keystone, apostrophe, and there are quite a few more) but since I got addicted to React in the meantime, I was not statisfied with any of them. But I found good ideas! Coupled with react, I thought, the possibilities would be amazing!

That's when I said: I will do websites again. But only with neutronJS! I have requests from people that want me to renew their old websites, so they have a lot of time waiting for neutron.

And that is needed, because I have currently no time for working on neutronJS and its hard to say when I'll be back to working on it. But I will do it. At least if no one is going to create a very similar CMS to neutronJS until then. 

There is no roadmap & not a finished plan of how the CMS will look like in the end. NeutronJS will change a lot. I'm not done with the API by far. I have a lot of cool things in mind =) And as long as I still change everything, it's impossible to contribute. There are also many mistakes I did that I want to fix first, before letting people build upon it.

So... I'm afraid all you can do is waiting or starting to build your own project. I really suggest not using neutronJS as a base for anything now.

**Comment by lennerd** [comment]
Thank your for the quick response. I definitely share many expirences you had – PHP as the first language, missing CMSs in node world and not fully satisfied with solutions like Apostrophe and Keystone.

Thank you for your honest input. I really looking forward to work with NeutronJS someday. Keep us informed. :wink:

**Comment by VanCoding** [comment]
You're welcome.

Of course I will keep people informed. Everytime someone stars the project and I see people are interested I'd like more and more to be able to tell people neutronJS is ready ;)
